//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIApplicationDelegate.h"

@class NSString, NSURL, RootViewController, UIWindow;

@interface JubeatAppDelegate : NSObject <UIApplicationDelegate>
{
    UIWindow *mainWindow;
    BOOL _gameCenterAvailable;
    BOOL _isRandom;
    BOOL _isMarkerLegal;
    RootViewController *_rootViewCtrl;
    NSString *_userAgent;
    int _deviceType;
    unsigned int _currentTheme;
    unsigned int _markerMax;
    NSString *_jcfDownloadID;
    NSURL *_notificationURL;
    NSString *_notificationTime;
}

+ (id)clientInfo;
+ (id)deviceName;
+ (id)appVersion;
+ (id)appCachesDirectory;
+ (id)appDocumentsDirectory;
+ (id)appLibraryDirectory;
+ (id)appDelegate;
+ (void)initialize;
@property(readonly, nonatomic) BOOL isMarkerLegal; // @synthesize isMarkerLegal=_isMarkerLegal;
@property(readonly, nonatomic) BOOL isRandom; // @synthesize isRandom=_isRandom;
@property(readonly, nonatomic) NSString *notificationTime; // @synthesize notificationTime=_notificationTime;
@property(readonly, nonatomic) NSURL *notificationURL; // @synthesize notificationURL=_notificationURL;
@property(readonly, nonatomic) NSString *jcfDownloadID; // @synthesize jcfDownloadID=_jcfDownloadID;
@property(readonly, nonatomic) unsigned int markerMax; // @synthesize markerMax=_markerMax;
@property(readonly, nonatomic) unsigned int currentTheme; // @synthesize currentTheme=_currentTheme;
@property(readonly, nonatomic) int deviceType; // @synthesize deviceType=_deviceType;
@property(readonly, nonatomic) BOOL gameCenterAvailable; // @synthesize gameCenterAvailable=_gameCenterAvailable;
@property(readonly, nonatomic) NSString *userAgent; // @synthesize userAgent=_userAgent;
@property(readonly, nonatomic) RootViewController *rootViewCtrl; // @synthesize rootViewCtrl=_rootViewCtrl;
- (void).cxx_destruct;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (BOOL)application:(id)arg1 handleOpenURL:(id)arg2;
- (void)markerDownloadComplete;
- (void)setRandomFlag:(BOOL)arg1;
- (void)setNotificationPageURL:(id)arg1 updateTime:(id)arg2;
- (void)resetDownLoadIndex;
- (id)musicListKey;
- (void)enableCopiousMarkers;
- (void)changeTheme:(unsigned int)arg1;
- (id)totalScoreLeaderboardCategory;
- (void)loginGameCenter;
- (void)disableGameCenter;
- (id)gameCenterName;
@property(readonly, nonatomic) BOOL isPadRetina;
@property(readonly, nonatomic) BOOL isPhoneRetina;
@property(readonly, nonatomic) BOOL isPad;

// Remaining properties
@property(retain, nonatomic) UIWindow *window;

@end

