//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class EAGLContext, NSArray, NSString, Texture2D;

@interface MarkerTestView : UIView
{
    EAGLContext *context;
    unsigned int defaultFramebuffer;
    unsigned int colorRenderbuffer;
    unsigned int elementArrayBuffer;
    Texture2D *texture[10];
    BOOL buttonPress;
    BOOL buttonPressOld;
    double baseTime;
    unsigned int state;
    BOOL isPad;
    BOOL isRetina;
    NSString *_currentMarker;
    NSArray *_soundNames;
}

+ (Class)layerClass;
@property(retain, nonatomic) NSArray *soundNames; // @synthesize soundNames=_soundNames;
@property(readonly) NSString *currentMarker; // @synthesize currentMarker=_currentMarker;
- (void).cxx_destruct;
- (void)dealloc;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)destroyFramebuffer;
- (void)draw;
- (void)reset;
- (void)releaseTex;
- (void)loadMarkerTex:(id)arg1;
- (BOOL)createFramebuffer;
- (id)initWithFrame:(struct CGRect)arg1;

@end

