//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RendererConf : NSObject
{
    unsigned int _markerID;
    unsigned int _diff;
    unsigned int _level;
    unsigned int _tuneID;
    NSString *_partnerName;
}

@property(retain, nonatomic) NSString *partnerName; // @synthesize partnerName=_partnerName;
@property(nonatomic) unsigned int tuneID; // @synthesize tuneID=_tuneID;
@property(nonatomic) unsigned int level; // @synthesize level=_level;
@property(nonatomic) unsigned int diff; // @synthesize diff=_diff;
@property(nonatomic) unsigned int markerID; // @synthesize markerID=_markerID;
- (void).cxx_destruct;

@end

